version: '2'
services:
    turtl:
        restart: always
        image: webofmars/turtl-docker
        volumes_from:
            - turtl-api-data
        ports:
            - '8181:8181'
        environment:
            - SITE_URL=https://turtl.example.com
            - ADMIN_EMAIL=root@example.com
            - LOCAL_UPLOAD_URL=http://turtl
            - FQDN=turtl
            - BINDADDR=0.0.0.0
    turtl-api-data:
        labels:
            - "com.example.description=turtl storage"
        entrypoint:
            - /bin/true
        image: busybox
        volumes:
            - /opt/api/uploads
            - /var/lib/rethinkdb/instance1
